services:
  db:
    image: mysql:5.7.44
    restart: always
    environment:
      MYSQL_DATABASE: chatdb
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: chatpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7.4.3-bookworm
    restart: always
    ports:
      - "6379:6379"

volumes:
  db_data:
